### ISSUE TITLE
Inconsistent Back-Navigation

### ISSUE THREAD

**Issue by pkritzinger** [noi-techpark/it.bz.noi.community#13]
Back-Navigation is not consistent, see Screenshot below - please always integrate "Zurück", i.e. "Back"

![Präsentation1](https://user-images.githubusercontent.com/92454516/141968305-e41e6fa3-8ab2-4069-9146-b0b365406411.png)

![meet](https://user-images.githubusercontent.com/92454516/141968137-bbd809fd-b785-4c63-9a9a-d0fe0292c4ea.PNG)

**Comment by matax87** [comment]
@pkritzinger I think you open the issue on the wrong repository. From the attached images I see that you are talking about the iOS app; thus, you need to open iOS's issue on shttps://github.com/noi-techpark/it.bz.noi.community.ios repository. Moreover I think that this is a duplicate of https://github.com/noi-techpark/it.bz.noi.community.ios/issues/51.

CC @Piiit

**Comment by pkritzinger** [comment]
ciao @matax87 - sorry for the confusion I'll close this issue again.
