### ISSUE TITLE
Switch to production environment

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/it.bz.noi.community#25]
- Use Keycloak Production environment (https://auth.opendatahub.bz.it/)
- Use Noi Community Api production environment (https://api.community.noi.opendatahub.bz.it)

**Comment by Piiit** [comment]
@RudiThoeni @sseppi I deploy this now

Wondering why we called it https://api.community.noi.opendatahub.bz.it, shouldn't it be https://community.api.opendatahub.bz.it?

We have https://tourism.api.opendatahub.bz.it/ and https://mobility.api.opendatahub.bz.it/ at the moment...

Not so important, but would be easier in the future to stick to a hierarchy within these names.

**Comment by Piiit** [comment]
@MarE1991 Done, lets wait for the reviews and releases of Apple and Google...
