### ISSUE TITLE
maps.noi.bz.it cookies on mobile app

### ISSUE THREAD

**Issue by matax87** [noi-techpark/it.bz.noi.community#28]
@RudiThoeni https://maps.noi.bz.it/it/?fullview=1&hidezoom=1 displays the cookies bar even if it shouldn't.

![img_6704f06646c8-1](https://user-images.githubusercontent.com/4108197/191274074-5c40ede7-ee04-441e-84c8-ab307af4e84c.jpg)

**Comment by RudiThoeni** [comment]
@sseppi how was this intended to solve, i think before there was no cookie banner?

**Comment by RudiThoeni** [comment]
maybe with the parameter fullview=1 to hide the cookie banner or by passing another parameter?

**Comment by sseppi** [comment]
> @sseppi how was this intended to solve, i think before there was no cookie banner?

@RudiThoeni yes, in the previous version we used a link with a specific parameter that opened maps without the cookie banner.

The parameter is `fullview=1`, I think that Henry, that implemented the new coockie banners in all websites, in this case inserted a little bug that we didn't discover till today.

**Comment by RudiThoeni** [comment]
ok i fixed this, when https://maps.noi.bz.it/en/?fullview=1 is passed the cookie banner is hidden....
maybe browser cache has to be cleared

**Comment by sseppi** [comment]
@RudiThoeni works on my Browsers (Firefox, Brave and Chrome)
