### ISSUE TITLE
NOI Onboarding

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community#6]
As an app user I want to find the Onboarding Manual with all the necessary information about NOI in order to be always updated about rules, rooms, etc.
At the moment, the manual is a pdf, but should be a digital product by autumn, ready to be implemented in the app. SO for the moment the app should integrate a link to the PDF or the webapp

**Comment by pkritzinger** [comment]
This is working perfectly fine, from my point of view we can close this issue. @Piiit @matax87

**Comment by Piiit** [comment]
@pkritzinger This is the webpage itself, is it also shown correclty on iOS? Some beta testers report that it is not shown

**Comment by pkritzinger** [comment]
@Piiit  - yes looks good. See screenshot below:
![IMG_4373](https://user-images.githubusercontent.com/92454516/141973650-61dd0438-b86b-4abe-aa3f-53b44f4c10be.PNG)
![IMG_4372](https://user-images.githubusercontent.com/92454516/141973655-5c50f462-e374-4545-9a96-93e32ef4ccd9.PNG)

**Comment by Piiit** [comment]
@pkritzinger Thx, closing.... it might be an update issue or caching problem on their phone... lets wait for additional details
