### ISSUE TITLE
NOI Maps Web Site to be integrated into the native apps

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.noi.community#7]
This is not about the NOI Community web application, but just the integration of maps.noi.bz.it into the native Android and iOS apps....

The already existing web application maps.noi.bz.it must be extended:

- [x] Add a URL parameter to hide the cookie banner, footer, language selector and title
- [x] Add a URL parameter to hide the zoom buttons

Both points need changes inside the web component and changes to the web page itself:
https://github.com/noi-techpark/it.bz.noi.maps and https://github.com/noi-techpark/webcomp-maps-noi

- [x] At this moment the zoom hide parameter inside the web component does not work and must be fixed
- [x] The full-view should not be inside the web component, but part of the web site
- [x] The web component needs additional parameters to hide the language menu and title (<-- invalid, since this things are part of the container webpage and not the web component itself, so the fullview parameter solves it already)

@pkritzinger and @madeincima Please discuss here if something has been misunderstood or is missing...

**Comment by Piiit** [comment]
@pkritzinger @madeincima @milena-gennara-madeincima please accept the invitations to this repo

**Comment by Piiit** [comment]
For those who do not know it already: The Kanban we use to track our progress is https://github.com/orgs/noi-techpark/projects/28

**Comment by madeincima** [comment]
Hello. We've made some changes and 2 pull requests, one inside the web component and one to the web page itself: 

- https://github.com/noi-techpark/webcomp-maps-noi/pull/16
- https://github.com/noi-techpark/it.bz.noi.maps/pull/29

Please rebuild/recompile noi_maps_widget.min.js from https://github.com/noi-techpark/webcomp-maps-noi and check in the html files (it/en/de) your hardcoded resource (es. https://github.com/noi-techpark/it.bz.noi.maps/blob/master/en/index.html  `<script src='https://cdn.webcomponents.opendatahub.testingmachine.eu/dist/9232cce6-2f39-11eb-adc1-0242ac120002/noi_maps_widget.min.js'></script>` ) is up-to-date.

After that you can use the hide the zoom and/or fullview functionalities.

**Hiding the zoom**
- using an URL parameter https://maps.noi.bz.it/en/?hidezoom=1
- change the inclusion inside the desidered html (es. inside https://github.com/noi-techpark/it.bz.noi.maps/blob/master/en/index.html like `<map-view language="en" totem="0" fullview="0" hidezoom="1"></map-view>` )

**Fullview**
- using an URL parameter https://maps.noi.bz.it/en/?fullview=1
- change the inclusion inside the desidered html (es. inside https://github.com/noi-techpark/it.bz.noi.maps/blob/master/en/index.html like `<map-view language="en" totem="0" fullview="1" hidezoom="0"></map-view>` )

Please let us know if everything's ok  :-)

**Comment by Piiit** [comment]
@pkritzinger Any news on this one?

**Comment by Piiit** [comment]
@madeincima 

> Please rebuild/recompile noi_maps_widget.min.js from https://github.com/noi-techpark/webcomp-maps-noi and check in the html files (it/en/de) your hardcoded resource (es. https://github.com/noi-techpark/it.bz.noi.maps/blob/master/en/index.html `<script src='https://cdn.webcomponents.opendatahub.testingmachine.eu/dist/9232cce6-2f39-11eb-adc1-0242ac120002/noi_maps_widget.min.js'></script>` ) is up-to-date.

Our CD always builds and deploys a new version of your code, the URL you see always takes the latest version from our test environment. You can see the versions in our staging web component store at https://webcomponents.opendatahub.testingmachine.eu/webcomponent/9232cce6-2f39-11eb-adc1-0242ac120002...

However, as you can test in that store, the new functionalities do not work.

> Please let us know if everything's ok :-)

Please have a look at the last PRs, the one for the web component was empty as we have discussed already it might just have been a merging issue.

When I test your changes locally with `docker-compose up` or `npm run start`, the functionalities for the hiding of zoom buttons etc. also do not work... 

Please fix the web component first, we look into the web site integration afterwards, thank you

**Comment by pkritzinger** [comment]
@Piiit from my point of view, the highlighted section in the screenshot below and the cookie-banner should be hidden.
`
![Screenshot_1](https://user-images.githubusercontent.com/92454516/141966128-d1a598e0-d0de-48bc-a79b-792c5c1fd46e.png)
`

**Comment by Piiit** [comment]
@pkritzinger Thx

**Comment by Piiit** [comment]
@madeincima Done, thx
